AWSTemplateFormatVersion: '2010-09-09'
Description: Public S3 Static Website with CloudFront and WAF

# CloudFormation: Public S3 Static Website with CloudFront and WAF
# This template provisions a public static website with:
# - Public S3 bucket accessible to everyone
# - CloudFront distribution serving the site over HTTPS
# - Optional AWS WAF protection for common web attacks

# ====================================================================================
# 1. Provider Configuration
# CloudFormation does not require an explicit provider block like Terraform.

# --------------------------
# Parameters
Parameters:
  BucketName:
    Type: String
    Default: achusec-public-s3-static-website-us-east-1  # Must be unique
    Description: Name of the S3 bucket
  DomainName:
    Type: String
    Default: example.com  # Optional if you want a domain alias on CloudFront
    Description: Fully qualified domain name for your site (optional)
  HostedZoneId:
    Type: String
    Default: ""  # Optional Route 53 Hosted Zone ID for domain alias
    Description: Route 53 Hosted Zone ID for your domain (optional)

# ====================================================================================
# 2. S3 Bucket (Public)
Resources:
  StaticSiteBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketName
      Tags:
        - Key: Name
          Value: StaticSiteBucket
        - Key: Environment
          Value: Dev
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        IgnorePublicAcls: false
        BlockPublicPolicy: false
        RestrictPublicBuckets: false

# ====================================================================================
# 3. S3 Bucket Policy (Public Read)
  StaticSiteBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref StaticSiteBucket
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal: "*"                  # Public access
            Action: s3:GetObject
            Resource: !Sub "${StaticSiteBucket.Arn}/*"

# ====================================================================================
# 4. WAF Web ACL (Optional)
  WAFWebACL:
    Type: AWS::WAFv2::WebACL
    Properties:
      Name: !Sub '${BucketName}-waf'
      Scope: CLOUDFRONT
      DefaultAction:
        Allow: {}
      VisibilityConfig:
        SampledRequestsEnabled: true
        CloudWatchMetricsEnabled: true
        MetricName: webACL
      Rules:
        - Name: AWSManagedRulesCommonRuleSet
          Priority: 1
          Statement:
            ManagedRuleGroupStatement:
              VendorName: AWS
              Name: AWSManagedRulesCommonRuleSet
          OverrideAction:
            None: {}
          VisibilityConfig:
            SampledRequestsEnabled: true
            CloudWatchMetricsEnabled: true
            MetricName: AWSManagedRulesCommonRuleSet

# ====================================================================================
# 5. CloudFront Distribution
  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    DependsOn: WAFWebACL
    Properties:
      DistributionConfig:
        Comment: CDN for static site
        Enabled: true
        WebACLId: !Ref WAFWebACL
        DefaultRootObject: index.html
        Origins:
          - Id: !Ref BucketName
            DomainName: !Sub '${BucketName}.s3.amazonaws.com'
            S3OriginConfig: {}
        DefaultCacheBehavior:
          TargetOriginId: !Ref BucketName
          ViewerProtocolPolicy: redirect-to-https
          AllowedMethods:
            - GET
            - HEAD
            - OPTIONS
          CachedMethods:
            - GET
            - HEAD
          ForwardedValues:
            QueryString: false
            Cookies:
              Forward: none
          MinTTL: 0
          DefaultTTL: 3600
          MaxTTL: 86400
        PriceClass: PriceClass_100
        ViewerCertificate:
          CloudFrontDefaultCertificate: true

# ====================================================================================
# 6. Route 53 DNS Record for Domain (Optional)
  WebsiteDNSRecord:
    Condition: HasDomainName
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZoneId
      Name: !Ref DomainName
      Type: A
      AliasTarget:
        DNSName: !GetAtt CloudFrontDistribution.DomainName
        HostedZoneId: Z2FDTNDATAQYW2  # CloudFront hosted zone ID

# ====================================================================================
# Outputs
Outputs:
  BucketName:
    Value: !Ref StaticSiteBucket
  BucketArn:
    Value: !GetAtt StaticSiteBucket.Arn
  CloudFrontDistributionId:
    Value: !Ref CloudFrontDistribution
  CloudFrontURL:
    Value: !GetAtt CloudFrontDistribution.DomainName
    Description: "CloudFront distribution domain name (URL)"