name: Deploy Static Website to AWS S3 + CloudFront

on:
  push:
    branches:
      - main
  paths:
    - 'terraform/private-with-acm/index.html'


jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # Step 3: Sync files to S3
      - name: Sync files to S3
        run: |
          aws s3 cp terraform/private-with-acm/index.html s3://${{ secrets.S3_BUCKET }}/index.html
            --delete \
            --exact-timestamps

      # Step 4: Invalidate CloudFront cache
      - name: Invalidate CloudFront cache
        run: |
          aws cloudfront create-invalidation \
            --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} \
            --paths "/*"
